version: '3'
services:
  dsw-server:
    image: datastewardshipwizard/wizard-server:3.16.2
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - minio
    volumes:
      - ./dsw.yml:/application/engine-wizard/config/application.yml:ro

  dsw-client:
    image: datastewardshipwizard/wizard-client:3.16.0
    restart: always
    ports:
      - 8080:80
    environment:
      API_URL: http://localhost:3000

  docworker:
    image: datastewardshipwizard/document-worker:3.16.0
    restart: always
    depends_on:
      - postgres
      - minio
      - dsw-server
    volumes:
      - ./dsw.yml:/app/config.yml:ro

  #mailer:
  #image: datastewardshipwizard/mailer:3.16.0
  #restart: always
  #depends_on:
  #- postgres
  #- dsw-server
  # volumes:
  #- ./dsw.yml:/app/config.yml:ro

  postgres:
    image: postgres:13.7
    restart: always
    # (!) Expose only for debugging locally or set-up authentication
    ports:
      - 127.0.0.1:15432:5432
    environment:
      POSTGRES_DB: engine-wizard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # (!) Mount for persistent data
    # volumes:
    #  - db-data:/var/lib/postgresql/data
    # OR
    #  - ./db-data/data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2022-08-02T23-59-16Z
    restart: always
    command: server /data --console-address ":9001"
    # (!) Expose only for debugging locally or set-up authentication
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9001:9001
    # (!) Mount and backup for persistent data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioPassword
    # (!) Mount for persistent data
    # volumes:
    #  - s3-data:/data
    # OR
    #  - ./s3-data/data:/data

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

  middleware:
    build: .
    image: 'middleware'
    environment:
      DMP_HOST: 'http://dsw-server:3000'
      DMP_TAG: '302b1584-a7a2-4d9c-9770-eee990b002ec'
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_USER: 'guest'
      RABBITMQ_PASSWORD: 'guest'
      PACKAGE_ID: 'myorg:panosc-expands:2.0.7'
      INGESTOR_EMAIL: 'albert.einstein@example.com'
      INGESTOR_PASSWORD: 'password'
    depends_on:
      - rabbitmq
      - dsw-server
    command:
      [
        './wait-for-it.sh',
        'rabbitmq:15672',
        '--timeout=30',
        '--',
        'node',
        './build/index.js',
      ]
# volumes:
#   db-data:
#   s3-data:
